import jax
import jax.numpy as jnp
import equinox as eqx
from typing import Callable, Optional, Any, Tuple

from .base import AbstractFilter


class SMCPHDState(eqx.Module):
    """
    State container for a Sequential Monte Carlo Probability Hypothesis Density (SMC-PHD) filter.

    Attributes:
        particles: Array of shape (num_particles, state_dim).
        weights: Array of shape (num_particles,) representing the weights of each particle.
                 The sum of these weights represents the expected number of targets.
        key: A JAX PRNGKey used for sampling.
    """

    particles: jnp.ndarray
    weights: jnp.ndarray
    key: jax.Array

    @property
    def expected_targets(self) -> jax.Array:
        """Expected number of targets (sum of weights)."""
        return jnp.sum(self.weights)


class SMCPHDFilter(AbstractFilter):
    """
    Sequential Monte Carlo Probability Hypothesis Density (SMC-PHD) Filter.

    Tracks an unknown and time-varying number of targets.
    """

    f: Callable
    h: Callable
    birth_model: Callable
    num_particles: int = eqx.field(static=True)
    num_birth_particles: int = eqx.field(static=True)
    P_S: float = eqx.field(static=True)
    P_D: float = eqx.field(static=True)
    clutter_intensity: float = eqx.field(static=True)
    Q: Optional[jax.Array] = None
    R: Optional[jax.Array] = None

    def __init__(
        self,
        f: Callable,
        h: Callable,
        birth_model: Callable,
        num_particles: int,
        num_birth_particles: int,
        P_S: float,
        P_D: float,
        clutter_intensity: float,
        Q: Optional[jax.Array] = None,
        R: Optional[jax.Array] = None,
    ):
        """
        Args:
            f: Transition function f(x) or f(x, u).
            h: Measurement function h(x).
            birth_model: Callable `birth_model(key, num_birth_particles) -> (particles, weights)`.
            num_particles: Number of particles to maintain after resampling.
            num_birth_particles: Number of particles generated by the birth model at each step.
            P_S: Probability of target survival.
            P_D: Probability of target detection.
            clutter_intensity: Mean number of clutter returns per unit volume (lambda_c).
            Q: Process noise covariance matrix.
            R: Measurement noise covariance matrix.
        """
        self.f = f
        self.h = h
        self.birth_model = birth_model
        self.num_particles = num_particles
        self.num_birth_particles = num_birth_particles
        self.P_S = float(P_S)
        self.P_D = float(P_D)
        self.clutter_intensity = float(clutter_intensity)
        self.Q = jnp.asarray(Q) if Q is not None else None
        self.R = jnp.asarray(R) if R is not None else None

    @eqx.filter_jit
    def predict(
        self, state: SMCPHDState, u: Optional[jax.Array] = None, params: Any = None
    ) -> SMCPHDState:
        """
        SMC-PHD prediction step: survival of existing particles and addition of newborn particles.
        """
        Q = params.Q if params is not None and hasattr(params, "Q") else self.Q
        assert Q is not None, "Process noise covariance Q must be provided."

        key, subkey1, subkey2 = jax.random.split(state.key, 3)

        # 1. Surviving particles
        if u is not None and u.size > 0:
            f_vmap = jax.vmap(lambda x: self.f(x, u))
        else:
            f_vmap = jax.vmap(self.f)

        p_surv_next = f_vmap(state.particles)
        state_dim = state.particles.shape[1]
        noise = jax.random.multivariate_normal(
            subkey1, mean=jnp.zeros(state_dim), cov=Q, shape=(state.particles.shape[0],)
        )
        p_surv_pred = p_surv_next + noise
        w_surv_pred = self.P_S * state.weights

        # 2. Birth particles
        p_birth, w_birth = self.birth_model(subkey2, self.num_birth_particles)

        # 3. Concatenate
        p_pred = jnp.vstack([p_surv_pred, p_birth])
        w_pred = jnp.concatenate([w_surv_pred, w_birth])

        return SMCPHDState(particles=p_pred, weights=w_pred, key=key)

    def _resample(
        self, particles: jnp.ndarray, weights: jnp.ndarray, key: jax.Array, expected_targets: float
    ) -> Tuple[jnp.ndarray, jnp.ndarray]:
        """
        Systematic resampling to maintain num_particles.
        """
        N = self.num_particles

        # Generate N uniformly distributed numbers
        positions = (jax.random.uniform(key) + jnp.arange(N)) / N

        # Compute cumulative sum of weights
        cum_weights = jnp.cumsum(weights)
        cum_weights = cum_weights / jnp.maximum(cum_weights[-1], 1e-15)

        # Find indices
        indices = jnp.searchsorted(cum_weights, positions)

        resampled_particles = particles[indices]
        
        # Distribute the total mass (expected targets) equally across the new particles
        reset_weights = jnp.full((N,), expected_targets / N)

        return resampled_particles, reset_weights

    @eqx.filter_jit
    def update(
        self,
        state: SMCPHDState,
        Z: jax.Array,
        params: Any = None,
        return_likelihood: bool = False,
    ):
        """
        SMC-PHD update step.
        Z should be a 2D array of shape (max_measurements, measurement_dim).
        Measurements padded with NaNs are ignored.
        """
        R = params.R if params is not None and hasattr(params, "R") else self.R
        assert R is not None, "Measurement noise covariance R must be provided."

        key, subkey = jax.random.split(state.key)

        h_vmap = jax.vmap(self.h)
        Z_pred = h_vmap(state.particles)  # shape: (num_particles + num_birth_particles, meas_dim)

        def meas_likelihood(z):
            """Calculates likelihood of a single measurement z across all predicted particles."""
            is_valid = ~jnp.isnan(z).any()
            z_safe = jnp.where(is_valid, z, jnp.zeros_like(z))
            lik = jax.scipy.stats.multivariate_normal.pdf(Z_pred, mean=z_safe, cov=R)
            return jnp.where(is_valid, lik, 0.0)

        # L_Z shape: (max_measurements, num_total_particles)
        L_Z = jax.vmap(meas_likelihood)(Z)

        w_pred = state.weights

        # 1. Missed detection component
        w_upd_missed = (1.0 - self.P_D) * w_pred

        # 2. Measurement update component
        def update_term(L_z):
            # L_z shape: (num_total_particles,)
            numerator = self.P_D * L_z * w_pred
            denominator = self.clutter_intensity + jnp.sum(numerator)
            return numerator / jnp.maximum(denominator, 1e-15)

        w_upd_meas = jax.vmap(update_term)(L_Z)  # shape: (max_measurements, num_total_particles)
        w_upd_meas_sum = jnp.sum(w_upd_meas, axis=0)  # shape: (num_total_particles,)

        # Total updated weights
        w_upd = w_upd_missed + w_upd_meas_sum

        expected_targets = jnp.sum(w_upd)
        w_norm = w_upd / jnp.maximum(expected_targets, 1e-15)

        # 3. Resample back to num_particles
        p_resampled, w_resampled = jax.lax.cond(
            expected_targets > 1e-6,
            lambda args: self._resample(args[0], args[1], args[2], args[3]),
            lambda args: (args[0][:self.num_particles], jnp.zeros(self.num_particles)),
            (state.particles, w_norm, subkey, expected_targets)
        )

        updated_state = SMCPHDState(particles=p_resampled, weights=w_resampled, key=key)

        if return_likelihood:
            return updated_state, 0.0  # Overall likelihood is complex for PHD, returning 0.0 placeholder
        return updated_state

    @eqx.filter_jit
    def run_step(
        self,
        state: SMCPHDState,
        Z: jax.Array,
        u: Optional[jax.Array] = None,
        params: Any = None,
        return_likelihood: bool = False,
    ):
        """
        Run a single predict-update step.
        """
        p_pred = self.predict(state, u, params)
        p_update = self.update(p_pred, Z, params, return_likelihood)
        return p_update

    @eqx.filter_jit
    def smooth_step(
        self,
        state: SMCPHDState,
        next_smoothed_state: SMCPHDState,
        u: Optional[jax.Array] = None,
        params: Any = None,
    ) -> SMCPHDState:
        raise NotImplementedError("Smoothing is not supported for SMC-PHD filters.")
